### ISSUE TITLE
Run paket update and then build?

### ISSUE THREAD

**Issue by cicicice** [opennars/ALANN2018#8]
Hi,

Apologies if this is somehow basic, I am new to this F# C# world but thought it would be fun to run the project. paket update went well, and then the instructions say build solution. Uh, not so easy, at least in VS 2019 "Build" is not an option for the solution, it is an option after I choose one of the projects. I chose ALANNServer.fsproj first, and hit an error immediately:

`1>------ Build started: Project: PriorityBuffer, Configuration: Debug|AnyCPU ------
  PriorityBuffer -> C:\Source\ALANN2018\PriorityBuffer\bin\Debug\PriorityBuffer.dll
2>------ Build started: Project: ALANNServer, Configuration: Debug|AnyCPU ------
C:\Source\ALANN2018\ALANNStreams\FSC : error FS0225: Source file 'C:\Source\ALANN2018\ALANNStreams\Inference\HigherOrderInference2.fs' could not be found
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

I will keep looking into it but I thought I should post here, I don't know if the projects have to be build in some particular order, but it would be optimal if the build was done on the command line as soon as paket update is run and we are still in the commandline.

**Comment by TonyLo1** [comment]
Thanks for raising this issue. It is now resolved. You can simply delete the reference to HigherOrderInference2.fs. The deletion was not reflected in the project file which is what caused the compile error. The project file has been updated now.

**Comment by patham9** [comment]
Schroedinger's Issue. :)
